// ACTION TYPES
// Actions that can be taken in the application - e.g. changed text, button presses, etc.

export const FIRST_NAME_CHANGED = "FIRST_NAME_CHANGED";
export const LAST_NAME_CHANGED = "LAST_NAME_CHANGED";
export const EMAIL_CHANGED = "EMAIL_CHANGED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const VOUCHER_CODE_CHANGED = "VOUCHER_CODE_CHANGED";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const SIGNUP_FORM = "SIGNUP_FORM";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const START_AUTH_LOADING = "START_AUTH_LOADING";
export const STOP_AUTH_LOADING = "STOP_AUTH_LOADING";

export const EMPLOYEE_UPDATE = "EMPLOYEE_UPDATE";
export const EMPLOYEE_CREATE = "EMPLOYEE_CREATE";
export const EMPLOYEE_FETCH = "EMPLOYEE_FETCH";
export const EMPLOYEES_FETCH_SUCCESS = "EMPLOYEES_FETCH_SUCCESS";
export const EMPLOYEE_SAVE_SUCCESS = "EMPLOYEES_SAVE_SUCCESS";
export const EMPLOYEE_STATE_RESET = "EMPLOYEE_STATE_RESET";


export const DECISION_UPDATE = "DECISION_UPDATE";
export const DECISION_CREATE = "DECISION_CREATE";
export const DECISION_STATE_RESET = "DECISION_STATE_RESET";
export const DECISION_SAVE_SUCCESS = "EMPLOYEES_SAVE_SUCCESS";
export const DECISIONS_FETCH_SUCCESS = "DECISIONS_FETCH_SUCCESS";
export const DECISION_FETCH_SUCCESS = "DECISION_FETCH_SUCCESS";
export const REGISTER_DECISION_ID = "REGISTER_DECISION_ID";
export const SELECTED_DECISION_STATE_RESET = "SELECTED_DECISION_STATE_RESET";
export const START_DECISION_LOADING = "START_DECISION_LOADING";
export const STOP_DECISION_LOADING = "STOP_DECISION_LOADING";

export const OPTIONS_FETCH_SUCCESS = "OPTIONS_FETCH_SUCCESS";
export const OPTION_CREATE = "OPTION_CREATE";
export const OPTION_UPDATE = "OPTION_UPDATE";
export const OPTION_STATE_RESET = "OPTION_STATE_RESET";
export const OPTION_SAVE_SUCCESS = "OPTION_SAVE_SUCCESS";
export const STOP_OPTION_LOADING = "STOP_OPTION_LOADING";
export const SCORE_OPTION = "SCORE_OPTION";
export const OPTIONS_STATE_RESET = "OPTIONS_STATE_RESET";
export const PAY_OPTION = "PAY_OPTION";

export const FACTORS_FETCH_SUCCESS = "FACTORS_FETCH_SUCCESS";
export const FACTOR_CREATE = "FACTOR_CREATE";
export const FACTOR_UPDATE = "FACTOR_UPDATE";
export const FACTORS_STATE_RESET = "FACTORS_STATE_RESET";
export const FACTOR_FORM_STATE_RESET = "FACTOR_FORM_STATE_RESET";
export const FACTOR_SAVE_SUCCESS = "FACTOR_SAVE_SUCCESS";
export const STOP_FACTOR_LOADING  = "STOP_FACTOR_LOADING";
export const WEIGHT_FACTOR = "WEIGHT_FACTOR";

export const IS_LOADING = "IS_LOADING";
export const RES_OPTION_SAVING = "RES_OPTION_SAVING";
export const RES_FACTOR_SAVING = "RES_FACTOR_SAVING";
